### PR TITLE
Ruff cleanup

### PR DESCRIPTION
**Pull request by daveisfera**
Cleans up the issues found by `ruff` after the changes from #336

### CODE REVIEW

**Comment by mauricioabreu** [comment]
That's HUGE! 👏🏼 

Thank you!

**Comment by mauricioabreu** [comment]
@daveisfera could you solve these conflicts? I think they were raised from your previous contributions

**Comment by daveisfera** [comment]
> @daveisfera could you solve these conflicts? I think they were raised from your previous contributions

Done

**Review by leandromoreira — APPROVED** [review]

**Comment by daveisfera** [comment]
I added an action to run `ruff` on pushes and pull requests

**Comment by daveisfera** [comment]
Could this PR and the others I submitted (#334 #335 #339) be merged? I'd love to get a release with these improvements out there (especially performance improvement that was already merged  #336)

**Comment by mauricioabreu** [comment]
@daveisfera yes. Could you rebase your PR against master? Then I will merge it.

**Comment by daveisfera** [comment]
Rebased and could #345 be merged as well so `timespec` can be used at the top level?
Thanks for all of your work on this project!

**Comment by mauricioabreu** [comment]
@daveisfera thank you for all your recent contributions. It means a lot.

**Comment by daveisfera** [comment]
> @daveisfera thank you for all your recent contributions. It means a lot.

Add one more to keep formatting consistent with `ruff`:
https://github.com/globocom/m3u8/pull/346

**Pull request merged**
