### PR TITLE
Extract SCTE35 metadata on every segments

### PR DESCRIPTION
**Pull request by birme**
Some HLS encoders (such as Elemental) provides the functionality to provide SCTE35 metadata on each segment in a period. This pull request adds the functionality to extract the SCTE35 metadata and duration.

### CODE REVIEW

**Comment by leandromoreira** [comment]
Thanks a lot @birme

**Comment by leandromoreira** [comment]
do you need a new build with this @birme ?

**Comment by birme** [comment]
That would be great!

**Comment by leandromoreira** [comment]
done! :) thanks again

**Pull request merged**
