### PR TITLE
remove redundant urlopen

### PR DESCRIPTION
**Pull request by lqs**

### CODE REVIEW

**Comment by leandromoreira** [comment]
Hi @lqs thanks for the contribution but it seems that this change made the [python2.6 stop to work](https://travis-ci.org/globocom/m3u8/builds/350151098?utm_source=github_status&utm_medium=notification)

**Comment by lqs** [comment]
@leandromoreira 
The test failure is caused by the current version of `arrow` library, which doesn't install the required `backports.functools_lru_cache` library on python 2.6 and caused an import error.

**Comment by leandromoreira** [comment]
nice, can you try to update this library in this branch to see if all the test will pass?

**Comment by lqs** [comment]
Added a `pip install backports.functools-lru-cache` in Python 2.x to workaround this issue.

**Comment by leandromoreira** [comment]
But now I'm wondering, is it worth? I mean, we swap a redundant call to some new conditional dependency =/ 

I do value your effort @lqs and again I want to thank you for the contribution but I'd like to let this redundant call instead.

I'm gonna put some others mainteiners on the loop as well @flavioribeiro @jbochi @igorsobreira @hltbra  what do you think?

**Comment by lqs** [comment]
@leandromoreira 
The new dependency is added to workaround the issue caused by the `arrow` library, not about 
 my fix of redundant call.

**Comment by newmaniese** [comment]
With the fixes in #120 the new requirement and the changes in `runtests` aren't needed. I vote we pull those and then this merge will be a good update.

**Comment by leandromoreira** [comment]
@newmaniese are you voting to close this PR or accept it now?

**Comment by newmaniese** [comment]
Accept it without the changes to `runtests`

**Pull request merged**
