### PR TITLE
Add #EXT-X-SESSION-KEY support

### PR DESCRIPTION
**Pull request by AntoineMonnet**
This PR adds ietf 8216 standard #EXT-X-SESSION-KEY support.
Most of it is a copy from #EXT-X-KEY handling.

Also adds #EXT-X-KEY in dumps.

### CODE REVIEW

**Comment by mauricioabreu** [comment]
Thank you for your contribution @AntoineMonnet 
Can you provide some tests?

**Comment by mauricioabreu** [comment]
Ping @AntoineMonnet

**Comment by AntoineMonnet** [comment]
@mauricioabreu should be better now !

**Comment by mauricioabreu** [comment]
Thank you! @AntoineMonnet

**Pull request merged**
