### PR TITLE
add timeout parameter for load function

### PR DESCRIPTION
**Pull request by hitzzc**
I met a case that my project hang on the load function because there is no timeout parameter. I think add timeout parameter into load function is better

### CODE REVIEW

**Comment by leandromoreira** [comment]
Thanks @hitzzc I'd ask you to provide test case for when using timeout though.

**Comment by hitzzc** [comment]
Hi @leandromoreira , sorry for my late reply. 
Test case has been added.

**Comment by leandromoreira** [comment]
thank you, so much, do you need a new version with   this?

**Comment by hitzzc** [comment]
Hi @leandromoreira , I don't need a new version with this. Thanks

**Pull request merged**
