### PR TITLE
FIX #104 - Error parsing line #EXT-X-MAP:URI="main.mp4",BYTERANGE="81…

### LINKED ISSUE #104: Error parsing line #EXT-X-MAP:URI="main.mp4",BYTERANGE="812@0"
Apple 'Advanced stream (HEVC/H.264)' reference has #EXT-X-MAP:URI="main.mp4",BYTERANGE="812@0" attribute. This attribute parses as segment_map_uri with incorrect value 'main.mp4",BYTERANGE="812@0'. But should be parsed as separate 'uri' and 'byterange'.

Link to m3u8:
https://tungsten.aaplimg.com/VOD/bipbop_adv_example_hevc/tp10/iframe_index.m3u8

Link to examples:
https://developer.apple.com/streaming/examples/

### PR DESCRIPTION
**Pull request by denex**
…2@0"

### CODE REVIEW

**Comment by leandromoreira** [comment]
Hi, @denex thank you for your contribution, it's much appreciated. I was reading the official docs for HLS and it seems that [we need to support both cases](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.5): When `URI` hasn't `BYTERANGE` and when it has.

**Comment by denex** [comment]
Yes I'll fix it asap

**Comment by leandromoreira** [comment]
Thank you very much @denex 👏 👏 👏 👏 👏 👏 👏 👏 👏  do you need a version with this feature soon?

**Comment by denex** [comment]
@leandromoreira Thank you for very neat library. It would be nice to have update )

**Pull request merged**
