### PR TITLE
dumps() include EXT-X-PROGRAM-DATE-TIME consistent with loads()

### PR DESCRIPTION
**Pull request by igorsobreira**
on Segment.dumps() instead of only writing EXT-X-PROGRAM-DATE-TIME
when EXT-X-DISCONTINUITY we always write when it was provided when
we parsed.

`Segment.program_date_time` is set only when EXT-X-PROGRAM-DATE-TIME is
present for that segment
Segment.current_program_date_time` is set when EXT-X-PROGRAM-DATE-TIME
is set for this segment or any previous ones

See discussion on globocom/m3u8#115

### CODE REVIEW

**Comment by igorsobreira** [comment]
See comments on #115

**Comment by mauricioabreu** [comment]
@igorsobreira thank you for your contribution.
Gonna read this soon and provide feedback if needed.

**Comment by mauricioabreu** [comment]
@igorsobreira thank you!
Will you provide more commits to this PR? If negative, I will merge it.

**Comment by igorsobreira** [comment]
> @igorsobreira thank you!
> Will you provide more commits to this PR? If negative, I will merge it.

Hi @mauricioabreu, what do you mean by "more commits"? Do you see something missing or some more tests I could add?

**Comment by mauricioabreu** [comment]
> > @igorsobreira thank you!
> > Will you provide more commits to this PR? If negative, I will merge it.
> 
> Hi @mauricioabreu, what do you mean by "more commits"? Do you see something missing or some more tests I could add?

Just checking if I could merge right away.

**Comment by igorsobreira** [comment]
Thanks!

**Pull request merged**
