### PR TITLE
Add support for (preliminary) low latency protocol extensions

### PR DESCRIPTION
**Pull request by davemevans**
This PR adds support for parsing and creating manifests using the new features added in https://developer.apple.com/documentation/http_live_streaming/protocol_extension_for_low-latency_hls_preliminary_specification, given the examples in that file.

`LAST-I-MSN` and` LAST-I-PART` are note included since they are marked as unused in the current spec.

### CODE REVIEW

**Comment by leandromoreira** [comment]
pretty neat! 👊

**Comment by mauricioabreu** [comment]
In order to merge this pull request, we need it rebased (it has some conflicting files). Can you rebase it please? @davemevans

**Comment by davemevans** [comment]
Sorry, I made a complete hash of the rebase. Should be fixed now. Probably worth squashing this one when merging 😉

**Comment by mauricioabreu** [comment]
@davemevans Done!
I will release a new version of `m3u8` tomorrow. Thank you again for the efforts here.

**Pull request merged**
