### PR TITLE
Add support for rendering REQ-VIDEO-LAYOUT in stream info classes

### PR DESCRIPTION
**Pull request by colekas-ssim**
REQ-VIDEO-LAYOUT is a relatively new tag within a stream info class - https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.4.3.8 (Page 48)

### CODE REVIEW

**Review by mauricioabreu — APPROVED** [review]
Thank you!

**Review by leandromoreira — COMMENTED** [review]
Can you add the tag in the readme?

**Comment by mauricioabreu** [comment]
@leandromoreira it is not a tag per se, it is a stream info attribute

**Comment by colekas-ssim** [comment]
I can something to the README.rst, but it doesn't look like it has a section for these types of additions... open to suggestions.

**Comment by mauricioabreu** [comment]
@colekas-ssim no need to. We currently just document tags, not specific attributes of each tag.

Thank you, merging!

**Pull request merged**
