### PR TITLE
Fixes #73 - Allow missing comma in EXTINF tag

### LINKED ISSUE #73: EXTINF tag with optional comma?
m3u8 library requires EXTINF tag to have title, but the title is optional, see https://tools.ietf.org/html/draft-pantos-http-live-streaming-09#section-3.3.2

### PR DESCRIPTION
**Pull request by ziima**

### CODE REVIEW

**Comment by leandromoreira** [comment]
Thanks @ziima can you fixe https://travis-ci.org/globocom/m3u8/jobs/154559924#L442 for python 3 ?

**Comment by ziima** [comment]
I think that's unrelated existing bug. This is just first time it's covered in tests.

**Comment by ziima** [comment]
The bug should be addressed in #78

**Comment by leandromoreira** [comment]
Thanks @ziima can you rebase it?

**Comment by ziima** [comment]
Rebased.

**Comment by leandromoreira** [comment]
Thank you @ziima 👍  do you need a new version with these changes?

**Comment by ziima** [comment]
Not necessarily, I can wait a while :)

**Pull request merged**
