### PR TITLE
Added support for #EXT-X-CUE-OUT-CONT tags as attributes of Segment

### PR DESCRIPTION
**Pull request by Neon-Dlea**

### CODE REVIEW

**Comment by flavioribeiro** [comment]
great, lgtm :+1:

**Comment by flavioribeiro** [comment]
cc @leandromoreira

**Comment by leandromoreira** [comment]
@flavioribeiro me too ! :+1:  thanks @Neon-Dlea

**Comment by leandromoreira** [comment]
@flavioribeiro I think we can accept this and generate a new version!

**Comment by leandromoreira** [comment]
thanks @Neon-Dlea :wave:

**Comment by flavioribeiro** [comment]
:beers:

**Pull request merged**
